# SPDX-FileCopyrightText: Copyright (c) 2022-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-ruby
install: |
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
merge:
  script: |
    bundle exec jekyll build
